language: node_js

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      node_js: lts/*
      script: npm run lint
    - stage: test
      node_js: 10
      script: npm test
    - node_js: 8
      script: npm test
    - node_js: 6
      script: npm test