language: node_js

stages:
  - lint
  - test
  - coverage

jobs:
  include:
    - stage: lint
      node_js: lts/*
      script: npm run lint
    - stage: test
      node_js: 10
      script: npm test
    - node_js: 8
      script: npm test
    - stage: coverage
      node_js: 8
      script: npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage